[build]
 command = "yarn build"
 publish = "dist"
 functions = "dist-functions"

[dev]
 command = "nuxt"

[[redirects]]
 from = "/store/product/hoodie"
 to = "/store/product/2019-hoodie"

[[redirects]]
 from = "/store/product/shirt"
 to = "/store/product/2019-shirt"

[[redirects]]
 from = "/store/basket"
 to = "/store/checkout"

[[headers]]
 for = "/*"

 [headers.values]
  Expect-CT = 'max-age=604800, report-uri="https://ldesgoui.report-uri.com/r/d/ct/enforce"'
  Feature-Policy = "default 'self'"
  NEL = '{"report_to":"default","max_age":31536000,"include_subdomains":true}'
  Referrer-Policy = "strict-origin-when-cross-origin"
  Report-To = '{"group":"default","max_age":31536000,"endpoints":[{"url":"https://ldesgoui.report-uri.com/a/d/g"}],"include_subdomains":true}'
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "DENY"
  X-Xss-Protection = "1; mode=block; report=https://ldesgoui.report-uri.com/r/d/xss/enforce"
